# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebfffc8503468b98b9354d46499179b23bfe3eb278d1c6efad3788e20dd15b1ec6d23de21159ad79ce2b2190a87a9dd098bc681ec74e730f9e8b00d8cbcbe309

test:
  secret_key_base: ac27a56ab4383fc35b017504cc52d5831acdf9d20ac098d2ed1285a1a020a3e3b6c8ec2c75d76c0c7960c61119cfdbd710217f353a67fc354b36dab67485370e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
